name: flutter_asistente_memoria
description: APP Asistente a la Memoria

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  formz: ^0.4.0-nullsafety.0
  firebase_core: ^1.0.3
  firebase_analytics: ^8.0.0
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.5
  weekday_selector: 1.0.0
  intl: ^0.17.0
  flutter_local_notifications: ^8.0.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

        
    
    
                                      